services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: sapporo-service-dev
    container_name: sapporo-service-dev
    volumes:
      - ${PWD}/sapporo:/app/sapporo
      - ${PWD}/tests:/app/tests
      # The ones below are mounted for cwltool and DinD.
      - ${PWD}/runs:${PWD}/runs
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    environment:
      # Priority: [CLI Args] -> [Env Vals] -> [Defaults]
      - SAPPORO_HOST=0.0.0.0
      - SAPPORO_PORT=1122
      - SAPPORO_DEBUG=True
      - SAPPORO_RUN_DIR=${PWD}/runs
    ports:
      - 127.0.0.1:1122:1122
    restart: on-failure
    working_dir: /app
    command: [ "sleep", "infinity" ]
    networks:
      - sapporo-dev-network

networks:
  sapporo-dev-network:
    name: sapporo-dev-network
